# mail@dongguochao.com

version: '2.2'

services:
  mysql:
    container_name: talentlib
    image: mysql:5.7.22
    ports:
       - 33306:3306
    volumes:
      # change './docker/mysql/volume' to your own path
      # WARNING: without this line, your data will be lost.
      - "./docker/mysql/volume:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "talentlib"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
